### ISSUE TITLE
noaa.get_forecasts() hangs

### ISSUE THREAD

**Issue by MiningMyBusiness** [paulokuong/noaa#14]
I've been using this codebase for the last two-three weeks. However, this morning (8am ET time US) the noaa.get_forecasts() function started hanging. It never returns the forecast.

**Comment by Cightline** [comment]
I'm having similar issues.

**Comment by tairabiteru** [comment]
Likewise. I also had the same issue when calling `get_observations()`. 
I did a bit of investigating, and it seems as though it hung when it made requests to `api.weather.gov/stations/{STATION}/observations`. When accessing this page normally, it presented me with an error, however as of around 1:20 PM EST, it seems as though the endpoint is responding normally again. It seems like this was an error on the end of the NWS.

**Comment by MiningMyBusiness** [comment]
Good to hear others are also having this issue. @tairabiteru Has this resolved for you when you call get_forecasts()? It still seems to be hanging for me when I call get_forecasts()

**Comment by tairabiteru** [comment]
Actually, I retract what I said before. The jury's still out. I've gotten a weird mix of it sometimes working and sometimes failing, but last I tried, I was getting consistent 502 errors from the URI. The same one I used in the above message. I did some more investigating into the issues with it, but decided to call it a night after about three hours of messing around and little to show for it.

I do still think it's the NWS though. I've noticed certain functions I've written to handle the data from the API suddenly quit working due (seemingly) to changes to the data coming from the API. I don't see how the library would affect that, especially since I've not run an update since this issue began. Regardless, I'll have a go again tomorrow probably.

**Comment by Cightline** [comment]
Everything is fine on my side again, I agree that it's probably the NWS.

**Comment by tairabiteru** [comment]
Well, I think this is our smoking gun:
[https://www.weather.gov/media/notification/scn19-113weather_api_updatesaab.pdf](url)

The NWS began upgrades to their API on February 5th. No word on when these upgrades would be completed, (or if they already have been) but seeing how these issues began on the 5th, I'd say that at least explains the instability. That, and the fact that I just got a response from a URI, and then a 500 error from the same exact URI not five minutes later.

**Comment by MiningMyBusiness** [comment]
It seems that issues are resolved for the time being. Will close this issue since it is not related to the code base.
